<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRa8t9GO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRa8t9GO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRa8t9GO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRa8t9GO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRa8t9GO\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ra8t9GO',
    'container.build_id' => '5f2d4b55',
    'container.build_time' => 1581978496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRa8t9GO');
