<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIYWxTPB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIYWxTPB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIYWxTPB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIYWxTPB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIYWxTPB\App_KernelDevDebugContainer([
    'container.build_hash' => 'IYWxTPB',
    'container.build_id' => '1ff5e38f',
    'container.build_time' => 1582593329,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIYWxTPB');
