<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_api_media_createvideoentry' => [[], ['_controller' => 'App\\Controller\\Api\\MediaController::createVideoEntry'], [], [['text', '/Api/CreateVideoEntry']], [], []],
    'app_api_media_createframe' => [[], ['_controller' => 'App\\Controller\\Api\\MediaController::CreateFrame'], [], [['text', '/Api/CreateFrame']], [], []],
    'app_api_media_convert' => [[], ['_controller' => 'App\\Controller\\Api\\MediaController::Convert'], [], [['text', '/Api/MediaConvert']], [], []],
];
