doctrine:
    dbal:
        #driver: pdo_mysql
        #host: '%env(resolve:DATABASE_HOST)%'
        #port: '%env(resolve:DATABASE_PORT)%'
        #dbname: '%env(resolve:DATABASE_NAME)%'
        #user: '%env(resolve:DATABASE_USER)%'
        #password: '%env(resolve:DATABASE_PASSWORD)%'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        #charset: UTF8
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        mapping_types:
            uuid_binary_ordered_time: binary
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
